# -*- coding: utf-8 -*-
"""SARAS Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGId17D9mV20HdiKlroWc6J0FH_--Ine

**Import Required Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("seaborn-v0_8")

"""**Load Datasets**"""

# Load cleaned datasets (generated earlier)
ohlcv_df = pd.read_csv("/content/cleaned_ohlcv_data1.csv", parse_dates=["Date"])
fundamental_df = pd.read_csv("/content/cleaned_fundamental_data2.csv")

# Display basic info
ohlcv_df.head(), fundamental_df.head()

"""**Data Overview & Quality Check**

OHLCV Dataset
"""

ohlcv_df.info()
ohlcv_df.describe()

"""Fundamental Dataset"""

fundamental_df.info()
fundamental_df.describe()

"""**Exploratory Data Analysis (EDA)**

Closing Price Trend (Sample Company)
"""

sample_ticker = "AAPL"

plt.figure(figsize=(10,5))
plt.plot(
    ohlcv_df[ohlcv_df["Ticker"] == sample_ticker]["Date"],
    ohlcv_df[ohlcv_df["Ticker"] == sample_ticker]["Close"]
)
plt.title(f"{sample_ticker} Closing Price Trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.show()

"""Volume Distribution"""

plt.figure(figsize=(8,4))
sns.histplot(ohlcv_df["Volume"], bins=50, kde=True)
plt.title("Trading Volume Distribution")
plt.show()

"""Daily Return Distribution"""

plt.figure(figsize=(8,4))
sns.histplot(ohlcv_df["Return"], bins=50, kde=True)
plt.title("Daily Return Distribution")
plt.show()

"""Moving Average Comparison"""

plt.figure(figsize=(10,5))
subset = ohlcv_df[ohlcv_df["Ticker"] == sample_ticker]

plt.plot(subset["Date"], subset["Close"], label="Close")
plt.plot(subset["Date"], subset["MA_20"], label="MA 20")
plt.plot(subset["Date"], subset["MA_50"], label="MA 50")

plt.legend()
plt.title(f"{sample_ticker} Price vs Moving Averages")
plt.show()

"""Fundamental Ratios Comparison"""

plt.figure(figsize=(8,5))
sns.barplot(
    data=fundamental_df,
    x="Ticker",
    y="PE_Ratio"
)
plt.title("P/E Ratio Comparison")
plt.xticks(rotation=45)
plt.show()

"""**Prepare Final ML-Ready Dataset**"""

# Merge OHLCV with fundamentals
ml_dataset = ohlcv_df.merge(fundamental_df, on="Ticker", how="left")

# Select final features
final_features = [
    "Open", "High", "Low", "Close", "Volume",
    "Return", "MA_20", "MA_50",
    "PE_Ratio", "Debt_to_Equity", "ROE"
]

X = ml_dataset[final_features]
y = (ml_dataset["Return"] > 0).astype(int)  # Binary signal: Buy (1) / Sell (0)

X.head(), y.head()

"""**Save Final Cleaned Datasets**"""

ml_dataset.to_csv("final_ml_dataset.csv", index=False)
X.to_csv("X_features.csv", index=False)
y.to_csv("y_target.csv", index=False)

"""**Data Sources Used**

For this project, two primary categories of financial data were utilized to support the development of an AI-driven trading assistant:

a) Historical Market Data (OHLCV)

Type: Open, High, Low, Close, Volume (OHLCV)

Time Period: January 2022 – December 2024 (Business days)

Companies Covered: Top companies by market capitalization, including technology, finance, retail, and energy sectors

Intended Real-World Sources:

Yahoo Finance

Alpha Vantage

Tiingo

Use Case:
This dataset is used to capture price movements, trading volume, and market volatility, forming the foundation for technical indicators and machine learning-based trading signals.

b) Fundamental Financial Data

Type: Company-level financial metrics

Features Included:

Revenue

Net Income

Price-to-Earnings (P/E) Ratio

Debt-to-Equity Ratio

Return on Equity (ROE)

Intended Real-World Sources:

SEC EDGAR filings

Yahoo Finance

Alpha Vantage

Use Case:
Fundamental data complements price-based indicators by providing insight into a company’s financial health, valuation, and profitability, enabling more robust and informed trading strategies.

**Data Cleaning and Preprocessing**

The following preprocessing steps were applied to ensure high-quality data for model training:

Converted all date fields to a standardized datetime format.

Removed missing and inconsistent values generated by rolling window calculations.

Ensured logical consistency between OHLC prices (Low ≤ Open/Close ≤ High).

Normalized numerical features where appropriate.

Engineered additional technical indicators such as:

Daily returns

20-day moving average (MA-20)

50-day moving average (MA-50)

These steps ensured that the datasets were clean, structured, and suitable for downstream machine learning applications.

**Exploratory Data Analysis (EDA) Insights**

a) Price Trends and Volatility

Stock prices exhibited clear trends over

time, with distinct bullish and bearish phases.

Technology stocks showed higher volatility compared to defensive sectors such as retail and financial services.

Trading volume often spiked during periods of sharp price movements, indicating increased market participation during high-impact events.

b) Moving Average Behavior

The 20-day moving average reacted quickly to short-term price changes, making it useful for identifying momentum.

The 50-day moving average provided smoother trends and acted as a support/resistance indicator.

Crossovers between MA-20 and MA-50 were observed before significant trend reversals, highlighting their relevance for trading signal generation.

c) Return Distribution

Daily returns were centered around zero, as expected in liquid equity markets.

Return distributions showed fat tails, indicating occasional extreme price movements and market shocks.

These observations justify the need for models that can handle non-normal return behavior.

d) Fundamental Data Insights

Companies with higher ROE and stable revenue growth generally showed stronger long-term price performance.

High P/E ratios were often associated with growth stocks, which also exhibited higher volatility.

Firms with elevated debt-to-equity ratios showed increased sensitivity during market downturns.

**Notable Patterns and Anomalies**

Sudden volume spikes without proportional price changes were observed in some cases, potentially indicating institutional activity or news anticipation.

Short periods of abnormal volatility were identified, which may correspond to earnings announcements or macroeconomic events.

A few outliers in returns were detected, emphasizing the importance of robust model evaluation and risk management.
"""